-- River Hub — M1 seed data
-- Run after migrations. Bootstraps the Friends of the Dart organisation,
-- reference data and the two MVP test types.
-- NOTE: the first admin auth user is created via the Supabase dashboard;
-- then insert their profile row (see README) — we cannot seed auth.users here.

-- ---------- Organisation ----------
insert into organisations (id, name, slug) values
  ('00000000-0000-0000-0000-000000000001', 'Friends of the Dart', 'friends-of-the-dart')
on conflict (slug) do nothing;

-- ---------- Water bodies (Dart catchment) ----------
insert into water_bodies (organisation_id, code, label) values
  ('00000000-0000-0000-0000-000000000001', '00001', 'Blackbrook River'),
  ('00000000-0000-0000-0000-000000000001', '00002', 'Cherry Brook'),
  ('00000000-0000-0000-0000-000000000001', '00003', 'Bidwell Brook'),
  ('00000000-0000-0000-0000-000000000001', '00004', 'Ashburn'),
  ('00000000-0000-0000-0000-000000000001', '00005', 'Dart'),
  ('00000000-0000-0000-0000-000000000001', '00006', 'West Dart River (Lower)'),
  ('00000000-0000-0000-0000-000000000001', '00007', 'Webburn')
on conflict (organisation_id, code) do nothing;

-- ---------- Test types (MVP: two only) ----------
insert into test_types
  (organisation_id, test_name, common_name, test_code, category, subcategory,
   measurement_type, primary_unit, regulatory_thresholds, threshold_source, health_risk_levels)
values
  ('00000000-0000-0000-0000-000000000001',
   'E. coli (culture)', 'E. coli (lab culture)', NULL, 'biological', 'Bacteria',
   'Quantitative', 'CFU/100mL',
   '{"bathing_water_excellent": "<=250 CFU/100mL", "bathing_water_good": "<=500 CFU/100mL", "drinking_water_standard": "0 CFU/100mL", "ecosystem_protection": "<=1000 CFU/100mL"}'::jsonb,
   'EU Bathing Water Directive', 'Green/Amber/Red'),
  ('00000000-0000-0000-0000-000000000001',
   'E. coli (Petrifilm)', 'E. coli (3M Petrifilm)', NULL, 'biological', 'Bacteria',
   'Quantitative', 'CFU/100mL',
   '{"bathing_water_excellent": "<=250 CFU/100mL", "bathing_water_good": "<=500 CFU/100mL"}'::jsonb,
   'EU Bathing Water Directive', 'Green/Amber/Red');

-- ---------- Parishes (Devon & Cornwall) ----------
insert into parishes (name, district, county) values
  ('All Saints', 'East Devon', 'Devon'),
  ('Awliscombe', 'East Devon', 'Devon'),
  ('Axminster', 'East Devon', 'Devon'),
  ('Axmouth', 'East Devon', 'Devon'),
  ('Aylesbeare', 'East Devon', 'Devon'),
  ('Beer', 'East Devon', 'Devon'),
  ('Bicton', 'East Devon', 'Devon'),
  ('Brampford Speke', 'East Devon', 'Devon'),
  ('Branscombe', 'East Devon', 'Devon'),
  ('Broadclyst', 'East Devon', 'Devon'),
  ('Broadhembury', 'East Devon', 'Devon'),
  ('Buckerell', 'East Devon', 'Devon'),
  ('Budleigh Salterton', 'East Devon', 'Devon'),
  ('Chardstock', 'East Devon', 'Devon'),
  ('Clyst Honiton', 'East Devon', 'Devon'),
  ('Clyst Hydon', 'East Devon', 'Devon'),
  ('Clyst St George', 'East Devon', 'Devon'),
  ('Clyst St Lawrence', 'East Devon', 'Devon'),
  ('Clyst St Mary', 'East Devon', 'Devon'),
  ('Colaton Raleigh', 'East Devon', 'Devon'),
  ('Colyford', 'East Devon', 'Devon'),
  ('Colyton', 'East Devon', 'Devon'),
  ('Combe Raleigh', 'East Devon', 'Devon'),
  ('Combpyne Rousdon', 'East Devon', 'Devon'),
  ('Cotleigh', 'East Devon', 'Devon'),
  ('Cranbrook', 'East Devon', 'Devon'),
  ('Dalwood', 'East Devon', 'Devon'),
  ('Dunkeswell', 'East Devon', 'Devon'),
  ('East Budleigh', 'East Devon', 'Devon'),
  ('Exmouth', 'East Devon', 'Devon'),
  ('Farringdon', 'East Devon', 'Devon'),
  ('Farway', 'East Devon', 'Devon'),
  ('Feniton', 'East Devon', 'Devon'),
  ('Gittisham', 'East Devon', 'Devon'),
  ('Hawkchurch', 'East Devon', 'Devon'),
  ('Honiton', 'East Devon', 'Devon'),
  ('Huxham', 'East Devon', 'Devon'),
  ('Kilmington', 'East Devon', 'Devon'),
  ('Lands common to Axminster and Kilmington', 'East Devon', 'Devon'),
  ('Luppitt', 'East Devon', 'Devon'),
  ('Lympstone', 'East Devon', 'Devon'),
  ('Membury', 'East Devon', 'Devon'),
  ('Monkton', 'East Devon', 'Devon'),
  ('Musbury', 'East Devon', 'Devon'),
  ('Nether Exe', 'East Devon', 'Devon'),
  ('Newton Poppleford and Harpford', 'East Devon', 'Devon'),
  ('Northleigh', 'East Devon', 'Devon'),
  ('Offwell', 'East Devon', 'Devon'),
  ('Otterton', 'East Devon', 'Devon'),
  ('Ottery St Mary', 'East Devon', 'Devon'),
  ('Payhembury', 'East Devon', 'Devon'),
  ('Plymtree', 'East Devon', 'Devon'),
  ('Poltimore', 'East Devon', 'Devon'),
  ('Rewe', 'East Devon', 'Devon'),
  ('Rockbeare', 'East Devon', 'Devon'),
  ('Seaton', 'East Devon', 'Devon'),
  ('Sheldon', 'East Devon', 'Devon'),
  ('Shute', 'East Devon', 'Devon'),
  ('Sidmouth', 'East Devon', 'Devon'),
  ('Southleigh', 'East Devon', 'Devon'),
  ('Sowton', 'East Devon', 'Devon'),
  ('Stockland', 'East Devon', 'Devon'),
  ('Stoke Canon', 'East Devon', 'Devon'),
  ('Talaton', 'East Devon', 'Devon'),
  ('Uplyme', 'East Devon', 'Devon'),
  ('Upottery', 'East Devon', 'Devon'),
  ('Upton Pyne', 'East Devon', 'Devon'),
  ('West Hill', 'East Devon', 'Devon'),
  ('Whimple', 'East Devon', 'Devon'),
  ('Widworthy', 'East Devon', 'Devon'),
  ('Woodbury', 'East Devon', 'Devon'),
  ('Yarcombe', 'East Devon', 'Devon'),
  ('Bampton', 'Mid Devon', 'Devon'),
  ('Bickleigh', 'Mid Devon', 'Devon'),
  ('Bow', 'Mid Devon', 'Devon'),
  ('Bradninch', 'Mid Devon', 'Devon'),
  ('Brushford', 'Mid Devon', 'Devon'),
  ('Burlescombe', 'Mid Devon', 'Devon'),
  ('Butterleigh', 'Mid Devon', 'Devon'),
  ('Cadbury', 'Mid Devon', 'Devon'),
  ('Cadeleigh', 'Mid Devon', 'Devon'),
  ('Chawleigh', 'Mid Devon', 'Devon'),
  ('Cheriton Bishop', 'Mid Devon', 'Devon'),
  ('Cheriton Fitzpaine', 'Mid Devon', 'Devon'),
  ('Clannaborough', 'Mid Devon', 'Devon'),
  ('Clayhanger', 'Mid Devon', 'Devon'),
  ('Clayhidon', 'Mid Devon', 'Devon'),
  ('Coldridge', 'Mid Devon', 'Devon'),
  ('Colebrooke', 'Mid Devon', 'Devon'),
  ('Copplestone', 'Mid Devon', 'Devon'),
  ('Crediton', 'Mid Devon', 'Devon'),
  ('Crediton Hamlets', 'Mid Devon', 'Devon'),
  ('Cruwys Morchard', 'Mid Devon', 'Devon'),
  ('Cullompton', 'Mid Devon', 'Devon'),
  ('Culmstock', 'Mid Devon', 'Devon'),
  ('Down St Mary', 'Mid Devon', 'Devon'),
  ('Eggesford', 'Mid Devon', 'Devon'),
  ('Halberton', 'Mid Devon', 'Devon'),
  ('Hemyock', 'Mid Devon', 'Devon'),
  ('Hittisleigh', 'Mid Devon', 'Devon'),
  ('Hockworthy', 'Mid Devon', 'Devon'),
  ('Holcombe Rogus', 'Mid Devon', 'Devon'),
  ('Huntsham', 'Mid Devon', 'Devon'),
  ('Kennerleigh', 'Mid Devon', 'Devon'),
  ('Kentisbeare', 'Mid Devon', 'Devon'),
  ('Lapford', 'Mid Devon', 'Devon'),
  ('Loxbeare', 'Mid Devon', 'Devon'),
  ('Morchard Bishop', 'Mid Devon', 'Devon'),
  ('Morebath', 'Mid Devon', 'Devon'),
  ('Newton St Cyres', 'Mid Devon', 'Devon'),
  ('Nymet Rowland', 'Mid Devon', 'Devon'),
  ('Oakford', 'Mid Devon', 'Devon'),
  ('Poughill', 'Mid Devon', 'Devon'),
  ('Puddington', 'Mid Devon', 'Devon'),
  ('Sampford Peverell', 'Mid Devon', 'Devon'),
  ('Sandford', 'Mid Devon', 'Devon'),
  ('Shobrooke', 'Mid Devon', 'Devon'),
  ('Silverton', 'Mid Devon', 'Devon'),
  ('Stockleigh English', 'Mid Devon', 'Devon'),
  ('Stockleigh Pomeroy', 'Mid Devon', 'Devon'),
  ('Stoodleigh', 'Mid Devon', 'Devon'),
  ('Templeton', 'Mid Devon', 'Devon'),
  ('Thelbridge', 'Mid Devon', 'Devon'),
  ('Thorverton', 'Mid Devon', 'Devon'),
  ('Tiverton', 'Mid Devon', 'Devon'),
  ('Uffculme', 'Mid Devon', 'Devon'),
  ('Uplowman', 'Mid Devon', 'Devon'),
  ('Upton Hellions', 'Mid Devon', 'Devon'),
  ('Washfield', 'Mid Devon', 'Devon'),
  ('Washford Pyne', 'Mid Devon', 'Devon'),
  ('Wembworthy', 'Mid Devon', 'Devon'),
  ('Willand', 'Mid Devon', 'Devon'),
  ('Woolfardisworthy', 'Mid Devon', 'Devon'),
  ('Zeal Monachorum', 'Mid Devon', 'Devon'),
  ('Arlington', 'North Devon', 'Devon'),
  ('Ashford', 'North Devon', 'Devon'),
  ('Atherington', 'North Devon', 'Devon'),
  ('Barnstaple', 'North Devon', 'Devon'),
  ('Berrynarbor', 'North Devon', 'Devon'),
  ('Bishop''s Nympton', 'North Devon', 'Devon'),
  ('Bishop''s Tawton', 'North Devon', 'Devon'),
  ('Bittadon', 'North Devon', 'Devon'),
  ('Bratton Fleming', 'North Devon', 'Devon'),
  ('Braunton', 'North Devon', 'Devon'),
  ('Brayford', 'North Devon', 'Devon'),
  ('Brendon and Countisbury', 'North Devon', 'Devon'),
  ('Burrington', 'North Devon', 'Devon'),
  ('Challacombe', 'North Devon', 'Devon'),
  ('Chittlehamholt', 'North Devon', 'Devon'),
  ('Chittlehampton', 'North Devon', 'Devon'),
  ('Chulmleigh', 'North Devon', 'Devon'),
  ('Combe Martin', 'North Devon', 'Devon'),
  ('East and West Buckland', 'North Devon', 'Devon'),
  ('East Anstey', 'North Devon', 'Devon'),
  ('East Down', 'North Devon', 'Devon'),
  ('East Worlington', 'North Devon', 'Devon'),
  ('Filleigh', 'North Devon', 'Devon'),
  ('Fremington', 'North Devon', 'Devon'),
  ('Georgeham', 'North Devon', 'Devon'),
  ('George Nympton', 'North Devon', 'Devon'),
  ('Goodleigh', 'North Devon', 'Devon'),
  ('Heanton Punchardon', 'North Devon', 'Devon'),
  ('Horwood, Lovacott and Newton Tracey', 'North Devon', 'Devon'),
  ('Ilfracombe', 'North Devon', 'Devon'),
  ('Instow', 'North Devon', 'Devon'),
  ('Kentisbury', 'North Devon', 'Devon'),
  ('King''s Nympton', 'North Devon', 'Devon'),
  ('Knowstone', 'North Devon', 'Devon'),
  ('Landkey', 'North Devon', 'Devon'),
  ('Loxhore', 'North Devon', 'Devon'),
  ('Lynton and Lynmouth', 'North Devon', 'Devon'),
  ('Mariansleigh', 'North Devon', 'Devon'),
  ('Martinhoe', 'North Devon', 'Devon'),
  ('Marwood', 'North Devon', 'Devon'),
  ('Meshaw', 'North Devon', 'Devon'),
  ('Molland', 'North Devon', 'Devon'),
  ('Mortehoe', 'North Devon', 'Devon'),
  ('North Molton', 'North Devon', 'Devon'),
  ('Parracombe', 'North Devon', 'Devon'),
  ('Pilton West', 'North Devon', 'Devon'),
  ('Queen''s Nympton', 'North Devon', 'Devon'),
  ('Rackenford', 'North Devon', 'Devon'),
  ('Romansleigh', 'North Devon', 'Devon'),
  ('Rose Ash', 'North Devon', 'Devon'),
  ('Satterleigh and Warkleigh', 'North Devon', 'Devon'),
  ('Shirwell', 'North Devon', 'Devon'),
  ('South Molton', 'North Devon', 'Devon'),
  ('Stoke Rivers', 'North Devon', 'Devon'),
  ('Swimbridge', 'North Devon', 'Devon'),
  ('Tawstock', 'North Devon', 'Devon'),
  ('Trentishoe', 'North Devon', 'Devon'),
  ('Twitchen', 'North Devon', 'Devon'),
  ('West Anstey', 'North Devon', 'Devon'),
  ('West Down', 'North Devon', 'Devon'),
  ('Westleigh', 'North Devon', 'Devon'),
  ('Witheridge', 'North Devon', 'Devon'),
  ('Ashprington', 'South Hams', 'Devon'),
  ('Aveton Gifford', 'South Hams', 'Devon'),
  ('Berry Pomeroy', 'South Hams', 'Devon'),
  ('Bickleigh', 'South Hams', 'Devon'),
  ('Bigbury', 'South Hams', 'Devon'),
  ('Blackawton', 'South Hams', 'Devon'),
  ('Brixton', 'South Hams', 'Devon'),
  ('Buckland Tout Saints', 'South Hams', 'Devon'),
  ('Charleton', 'South Hams', 'Devon'),
  ('Chivelstone', 'South Hams', 'Devon'),
  ('Churchstow', 'South Hams', 'Devon'),
  ('Cornwood', 'South Hams', 'Devon'),
  ('Cornworthy', 'South Hams', 'Devon'),
  ('Dartington', 'South Hams', 'Devon'),
  ('Dartmouth', 'South Hams', 'Devon'),
  ('Dean Prior', 'South Hams', 'Devon'),
  ('Diptford', 'South Hams', 'Devon'),
  ('Dittisham', 'South Hams', 'Devon'),
  ('East Allington', 'South Hams', 'Devon'),
  ('East Portlemouth', 'South Hams', 'Devon'),
  ('Ermington', 'South Hams', 'Devon'),
  ('Frogmore and Sherford', 'South Hams', 'Devon'),
  ('Halwell and Moreleigh', 'South Hams', 'Devon'),
  ('Harberton', 'South Hams', 'Devon'),
  ('Harford', 'South Hams', 'Devon'),
  ('Holbeton', 'South Hams', 'Devon'),
  ('Holne', 'South Hams', 'Devon'),
  ('Ivybridge', 'South Hams', 'Devon'),
  ('Kingsbridge', 'South Hams', 'Devon'),
  ('Kingston', 'South Hams', 'Devon'),
  ('Kingswear', 'South Hams', 'Devon'),
  ('Littlehempston', 'South Hams', 'Devon'),
  ('Loddiswell', 'South Hams', 'Devon'),
  ('Malborough', 'South Hams', 'Devon'),
  ('Marldon', 'South Hams', 'Devon'),
  ('Modbury', 'South Hams', 'Devon'),
  ('Newton and Noss', 'South Hams', 'Devon'),
  ('North Huish', 'South Hams', 'Devon'),
  ('Rattery', 'South Hams', 'Devon'),
  ('Ringmore', 'South Hams', 'Devon'),
  ('Salcombe', 'South Hams', 'Devon'),
  ('Shaugh Prior', 'South Hams', 'Devon'),
  ('Slapton', 'South Hams', 'Devon'),
  ('South Brent', 'South Hams', 'Devon'),
  ('South Huish', 'South Hams', 'Devon'),
  ('South Milton', 'South Hams', 'Devon'),
  ('South Pool', 'South Hams', 'Devon'),
  ('Sparkwell', 'South Hams', 'Devon'),
  ('Staverton', 'South Hams', 'Devon'),
  ('Stoke Fleming', 'South Hams', 'Devon'),
  ('Stoke Gabriel', 'South Hams', 'Devon'),
  ('Stokenham', 'South Hams', 'Devon'),
  ('Strete', 'South Hams', 'Devon'),
  ('Thurlestone', 'South Hams', 'Devon'),
  ('Totnes', 'South Hams', 'Devon'),
  ('Ugborough', 'South Hams', 'Devon'),
  ('Wembury', 'South Hams', 'Devon'),
  ('West Alvington', 'South Hams', 'Devon'),
  ('West Buckfastleigh', 'South Hams', 'Devon'),
  ('Woodleigh', 'South Hams', 'Devon'),
  ('Yealmpton', 'South Hams', 'Devon'),
  ('Abbotskerswell', 'Teignbridge', 'Devon'),
  ('Ashburton', 'Teignbridge', 'Devon'),
  ('Ashcombe', 'Teignbridge', 'Devon'),
  ('Ashton', 'Teignbridge', 'Devon'),
  ('Bickington', 'Teignbridge', 'Devon'),
  ('Bishopsteignton', 'Teignbridge', 'Devon'),
  ('Bovey Tracey', 'Teignbridge', 'Devon'),
  ('Bridford', 'Teignbridge', 'Devon'),
  ('Broadhempston', 'Teignbridge', 'Devon'),
  ('Buckfastleigh', 'Teignbridge', 'Devon'),
  ('Buckland-in-the-Moor', 'Teignbridge', 'Devon'),
  ('Christow', 'Teignbridge', 'Devon'),
  ('Chudleigh', 'Teignbridge', 'Devon'),
  ('Coffinswell', 'Teignbridge', 'Devon'),
  ('Dawlish', 'Teignbridge', 'Devon'),
  ('Denbury and Torbryan', 'Teignbridge', 'Devon'),
  ('Doddiscombsleigh', 'Teignbridge', 'Devon'),
  ('Dunchideock', 'Teignbridge', 'Devon'),
  ('Dunsford', 'Teignbridge', 'Devon'),
  ('Exminster', 'Teignbridge', 'Devon'),
  ('Haccombe with Combe', 'Teignbridge', 'Devon'),
  ('Hennock', 'Teignbridge', 'Devon'),
  ('Holcombe Burnell', 'Teignbridge', 'Devon'),
  ('Ide', 'Teignbridge', 'Devon'),
  ('Ideford', 'Teignbridge', 'Devon'),
  ('Ilsington', 'Teignbridge', 'Devon'),
  ('Ipplepen', 'Teignbridge', 'Devon'),
  ('Kenn', 'Teignbridge', 'Devon'),
  ('Kenton', 'Teignbridge', 'Devon'),
  ('Kingskerswell', 'Teignbridge', 'Devon'),
  ('Kingsteignton', 'Teignbridge', 'Devon'),
  ('Lustleigh', 'Teignbridge', 'Devon'),
  ('Mamhead', 'Teignbridge', 'Devon'),
  ('Manaton', 'Teignbridge', 'Devon'),
  ('Moretonhampstead', 'Teignbridge', 'Devon'),
  ('Newton Abbot', 'Teignbridge', 'Devon'),
  ('North Bovey', 'Teignbridge', 'Devon'),
  ('Ogwell', 'Teignbridge', 'Devon'),
  ('Powderham', 'Teignbridge', 'Devon'),
  ('Shaldon', 'Teignbridge', 'Devon'),
  ('Shillingford St George', 'Teignbridge', 'Devon'),
  ('Starcross', 'Teignbridge', 'Devon'),
  ('Stokeinteignhead', 'Teignbridge', 'Devon'),
  ('Tedburn St Mary', 'Teignbridge', 'Devon'),
  ('Teigngrace', 'Teignbridge', 'Devon'),
  ('Teignmouth', 'Teignbridge', 'Devon'),
  ('Trusham', 'Teignbridge', 'Devon'),
  ('Whitestone', 'Teignbridge', 'Devon'),
  ('Widecombe in the Moor', 'Teignbridge', 'Devon'),
  ('Woodland', 'Teignbridge', 'Devon'),
  ('Brixham', 'Torbay', 'Devon'),
  ('Abbots Bickington', 'Torridge', 'Devon'),
  ('Abbotsham', 'Torridge', 'Devon'),
  ('Alverdiscott', 'Torridge', 'Devon'),
  ('Alwington', 'Torridge', 'Devon'),
  ('Ashreigney', 'Torridge', 'Devon'),
  ('Ashwater', 'Torridge', 'Devon'),
  ('Beaford', 'Torridge', 'Devon'),
  ('Bideford', 'Torridge', 'Devon'),
  ('Black Torrington', 'Torridge', 'Devon'),
  ('Bradford', 'Torridge', 'Devon'),
  ('Bradworthy', 'Torridge', 'Devon'),
  ('Bridgerule', 'Torridge', 'Devon'),
  ('Broadwoodwidger', 'Torridge', 'Devon'),
  ('Buckland Brewer', 'Torridge', 'Devon'),
  ('Buckland Filleigh', 'Torridge', 'Devon'),
  ('Bulkworthy', 'Torridge', 'Devon'),
  ('Clawton', 'Torridge', 'Devon'),
  ('Clovelly', 'Torridge', 'Devon'),
  ('Cookbury', 'Torridge', 'Devon'),
  ('Dolton', 'Torridge', 'Devon'),
  ('Dowland', 'Torridge', 'Devon'),
  ('East Putford', 'Torridge', 'Devon'),
  ('Frithelstock', 'Torridge', 'Devon'),
  ('Great Torrington', 'Torridge', 'Devon'),
  ('Halwill', 'Torridge', 'Devon'),
  ('Hartland', 'Torridge', 'Devon'),
  ('High Bickington', 'Torridge', 'Devon'),
  ('Hollacombe', 'Torridge', 'Devon'),
  ('Holsworthy', 'Torridge', 'Devon'),
  ('Holsworthy Hamlets', 'Torridge', 'Devon'),
  ('Huish', 'Torridge', 'Devon'),
  ('Huntshaw', 'Torridge', 'Devon'),
  ('Landcross', 'Torridge', 'Devon'),
  ('Langtree', 'Torridge', 'Devon'),
  ('Littleham', 'Torridge', 'Devon'),
  ('Little Torrington', 'Torridge', 'Devon'),
  ('Luffincott', 'Torridge', 'Devon'),
  ('Merton', 'Torridge', 'Devon'),
  ('Milton Damerel', 'Torridge', 'Devon'),
  ('Monkleigh', 'Torridge', 'Devon'),
  ('Newton St Petrock', 'Torridge', 'Devon'),
  ('Northam', 'Torridge', 'Devon'),
  ('Northcott', 'Torridge', 'Devon'),
  ('Pancrasweek', 'Torridge', 'Devon'),
  ('Parkham', 'Torridge', 'Devon'),
  ('Peters Marland', 'Torridge', 'Devon'),
  ('Petrockstow', 'Torridge', 'Devon'),
  ('Pyworthy', 'Torridge', 'Devon'),
  ('Roborough', 'Torridge', 'Devon'),
  ('Shebbear', 'Torridge', 'Devon'),
  ('Sheepwash', 'Torridge', 'Devon'),
  ('St Giles in the Wood', 'Torridge', 'Devon'),
  ('St Giles on the Heath', 'Torridge', 'Devon'),
  ('Sutcombe', 'Torridge', 'Devon'),
  ('Tetcott', 'Torridge', 'Devon'),
  ('Thornbury', 'Torridge', 'Devon'),
  ('Virginstow', 'Torridge', 'Devon'),
  ('Weare Giffard', 'Torridge', 'Devon'),
  ('Welcombe', 'Torridge', 'Devon'),
  ('West Putford', 'Torridge', 'Devon'),
  ('Winkleigh', 'Torridge', 'Devon'),
  ('Woolfardisworthy', 'Torridge', 'Devon'),
  ('Yarnscombe', 'Torridge', 'Devon'),
  ('Beaworthy', 'West Devon', 'Devon'),
  ('Belstone', 'West Devon', 'Devon'),
  ('Bere Ferrers', 'West Devon', 'Devon'),
  ('Bondleigh', 'West Devon', 'Devon'),
  ('Bradstone', 'West Devon', 'Devon'),
  ('Bratton Clovelly', 'West Devon', 'Devon'),
  ('Brentor', 'West Devon', 'Devon'),
  ('Bridestowe', 'West Devon', 'Devon'),
  ('Bridestowe and Sourton Common', 'West Devon', 'Devon'),
  ('Broadwoodkelly', 'West Devon', 'Devon'),
  ('Buckland Monachorum', 'West Devon', 'Devon'),
  ('Chagford', 'West Devon', 'Devon'),
  ('Coryton', 'West Devon', 'Devon'),
  ('Dartmoor Forest', 'West Devon', 'Devon'),
  ('Drewsteignton', 'West Devon', 'Devon'),
  ('Dunterton', 'West Devon', 'Devon'),
  ('Exbourne', 'West Devon', 'Devon'),
  ('Germansweek', 'West Devon', 'Devon'),
  ('Gidleigh', 'West Devon', 'Devon'),
  ('Gulworthy', 'West Devon', 'Devon'),
  ('Hatherleigh', 'West Devon', 'Devon'),
  ('Highampton', 'West Devon', 'Devon'),
  ('Horrabridge', 'West Devon', 'Devon'),
  ('Iddesleigh', 'West Devon', 'Devon'),
  ('Inwardleigh', 'West Devon', 'Devon'),
  ('Jacobstowe', 'West Devon', 'Devon'),
  ('Kelly', 'West Devon', 'Devon'),
  ('Lamerton', 'West Devon', 'Devon'),
  ('Lewtrenchard', 'West Devon', 'Devon'),
  ('Lifton', 'West Devon', 'Devon'),
  ('Lydford', 'West Devon', 'Devon'),
  ('Marystow', 'West Devon', 'Devon'),
  ('Mary Tavy', 'West Devon', 'Devon'),
  ('Meavy', 'West Devon', 'Devon'),
  ('Meeth', 'West Devon', 'Devon'),
  ('Milton Abbot', 'West Devon', 'Devon'),
  ('Monkokehampton', 'West Devon', 'Devon'),
  ('North Tawton', 'West Devon', 'Devon'),
  ('Northlew', 'West Devon', 'Devon'),
  ('Okehampton', 'West Devon', 'Devon'),
  ('Okehampton Hamlets', 'West Devon', 'Devon'),
  ('Peter Tavy', 'West Devon', 'Devon'),
  ('Sampford Courtenay', 'West Devon', 'Devon'),
  ('Sampford Spiney', 'West Devon', 'Devon'),
  ('Sheepstor', 'West Devon', 'Devon'),
  ('Sourton', 'West Devon', 'Devon'),
  ('South Tawton', 'West Devon', 'Devon'),
  ('Spreyton', 'West Devon', 'Devon'),
  ('Sticklepath', 'West Devon', 'Devon'),
  ('Stowford', 'West Devon', 'Devon'),
  ('Sydenham Damerel', 'West Devon', 'Devon'),
  ('Tavistock', 'West Devon', 'Devon'),
  ('Throwleigh', 'West Devon', 'Devon'),
  ('Thrushelton', 'West Devon', 'Devon'),
  ('Walkhampton', 'West Devon', 'Devon'),
  ('Whitchurch', 'West Devon', 'Devon'),
  ('Advent', 'Cornwall', 'Cornwall'),
  ('Altarnun', 'Cornwall', 'Cornwall'),
  ('Antony', 'Cornwall', 'Cornwall'),
  ('Blisland', 'Cornwall', 'Cornwall'),
  ('Boconnoc', 'Cornwall', 'Cornwall'),
  ('Bodmin', 'Cornwall', 'Cornwall'),
  ('Botusfleming', 'Cornwall', 'Cornwall'),
  ('Boyton', 'Cornwall', 'Cornwall'),
  ('Breage', 'Cornwall', 'Cornwall'),
  ('Braddock', 'Cornwall', 'Cornwall'),
  ('Bryher', 'Cornwall', 'Cornwall'),
  ('Bude–Stratton', 'Cornwall', 'Cornwall'),
  ('Budock', 'Cornwall', 'Cornwall'),
  ('Callington', 'Cornwall', 'Cornwall'),
  ('Calstock', 'Cornwall', 'Cornwall'),
  ('Camborne', 'Cornwall', 'Cornwall'),
  ('Camelford', 'Cornwall', 'Cornwall'),
  ('Cardinham', 'Cornwall', 'Cornwall'),
  ('Carharrack', 'Cornwall', 'Cornwall'),
  ('Carlyon', 'Cornwall', 'Cornwall'),
  ('Carn Brea', 'Cornwall', 'Cornwall'),
  ('Chacewater', 'Cornwall', 'Cornwall'),
  ('Colan', 'Cornwall', 'Cornwall'),
  ('Constantine', 'Cornwall', 'Cornwall'),
  ('Crantock', 'Cornwall', 'Cornwall'),
  ('Crowan', 'Cornwall', 'Cornwall'),
  ('Cubert', 'Cornwall', 'Cornwall'),
  ('Cury', 'Cornwall', 'Cornwall'),
  ('Davidstow', 'Cornwall', 'Cornwall'),
  ('Delabole', 'Cornwall', 'Cornwall'),
  ('Deviock', 'Cornwall', 'Cornwall'),
  ('Dobwalls', 'Cornwall', 'Cornwall'),
  ('Duloe', 'Cornwall', 'Cornwall'),
  ('Egloshayle', 'Cornwall', 'Cornwall'),
  ('Egloskerry', 'Cornwall', 'Cornwall'),
  ('Falmouth', 'Cornwall', 'Cornwall'),
  ('Feock', 'Cornwall', 'Cornwall'),
  ('Forrabury and Minster', 'Cornwall', 'Cornwall'),
  ('Fowey', 'Cornwall', 'Cornwall'),
  ('Germoe', 'Cornwall', 'Cornwall'),
  ('Gerrans', 'Cornwall', 'Cornwall'),
  ('Grade–Ruan', 'Cornwall', 'Cornwall'),
  ('Grampound with Creed', 'Cornwall', 'Cornwall'),
  ('Gunwalloe', 'Cornwall', 'Cornwall'),
  ('Gweek', 'Cornwall', 'Cornwall'),
  ('Gwennap', 'Cornwall', 'Cornwall'),
  ('Gwinear–Gwithian', 'Cornwall', 'Cornwall'),
  ('Hayle', 'Cornwall', 'Cornwall'),
  ('Helland', 'Cornwall', 'Cornwall'),
  ('Helston', 'Cornwall', 'Cornwall'),
  ('Illogan', 'Cornwall', 'Cornwall'),
  ('Jacobstow', 'Cornwall', 'Cornwall'),
  ('Kea', 'Cornwall', 'Cornwall'),
  ('Kenwyn', 'Cornwall', 'Cornwall'),
  ('Kilkhampton', 'Cornwall', 'Cornwall'),
  ('Ladock', 'Cornwall', 'Cornwall'),
  ('Landewednack', 'Cornwall', 'Cornwall'),
  ('Landrake with', 'Cornwall', 'Cornwall'),
  ('Landulph', 'Cornwall', 'Cornwall'),
  ('Laneast', 'Cornwall', 'Cornwall'),
  ('Lanhydrock', 'Cornwall', 'Cornwall'),
  ('Lanivet', 'Cornwall', 'Cornwall'),
  ('Lanlivery', 'Cornwall', 'Cornwall'),
  ('Lanner', 'Cornwall', 'Cornwall'),
  ('Lanreath', 'Cornwall', 'Cornwall'),
  ('Lanteglos', 'Cornwall', 'Cornwall'),
  ('Launcells', 'Cornwall', 'Cornwall'),
  ('Launceston', 'Cornwall', 'Cornwall'),
  ('Lawhitton Rural', 'Cornwall', 'Cornwall'),
  ('Lesnewth', 'Cornwall', 'Cornwall'),
  ('Lewannick', 'Cornwall', 'Cornwall'),
  ('Lezant', 'Cornwall', 'Cornwall'),
  ('Linkinhorne', 'Cornwall', 'Cornwall'),
  ('Liskeard', 'Cornwall', 'Cornwall'),
  ('Looe', 'Cornwall', 'Cornwall'),
  ('Lostwithiel', 'Cornwall', 'Cornwall'),
  ('Ludgvan', 'Cornwall', 'Cornwall'),
  ('Luxulyan', 'Cornwall', 'Cornwall'),
  ('Mabe', 'Cornwall', 'Cornwall'),
  ('Madron', 'Cornwall', 'Cornwall'),
  ('Maker-with-Rame', 'Cornwall', 'Cornwall'),
  ('Manaccan', 'Cornwall', 'Cornwall'),
  ('Marazion', 'Cornwall', 'Cornwall'),
  ('Marhamchurch', 'Cornwall', 'Cornwall'),
  ('Mawgan-in-Meneage', 'Cornwall', 'Cornwall'),
  ('Mawgan-in-Pydar', 'Cornwall', 'Cornwall'),
  ('Mawnan', 'Cornwall', 'Cornwall'),
  ('Menheniot', 'Cornwall', 'Cornwall'),
  ('Mevagissey', 'Cornwall', 'Cornwall'),
  ('Michaelstow', 'Cornwall', 'Cornwall'),
  ('Millbrook', 'Cornwall', 'Cornwall'),
  ('Morvah', 'Cornwall', 'Cornwall'),
  ('Morval', 'Cornwall', 'Cornwall'),
  ('Morwenstow', 'Cornwall', 'Cornwall'),
  ('Mullion', 'Cornwall', 'Cornwall'),
  ('Mylor', 'Cornwall', 'Cornwall'),
  ('Newquay', 'Cornwall', 'Cornwall'),
  ('North Hill', 'Cornwall', 'Cornwall'),
  ('North Petherwin', 'Cornwall', 'Cornwall'),
  ('North Tamerton', 'Cornwall', 'Cornwall'),
  ('Otterham', 'Cornwall', 'Cornwall'),
  ('Padstow', 'Cornwall', 'Cornwall'),
  ('Pelynt', 'Cornwall', 'Cornwall'),
  ('Penryn', 'Cornwall', 'Cornwall'),
  ('Pentewan Valley', 'Cornwall', 'Cornwall'),
  ('Penzance', 'Cornwall', 'Cornwall'),
  ('Perranarworthal', 'Cornwall', 'Cornwall'),
  ('Perranuthnoe', 'Cornwall', 'Cornwall'),
  ('Perranzabuloe', 'Cornwall', 'Cornwall'),
  ('Philleigh', 'Cornwall', 'Cornwall'),
  ('Pillaton', 'Cornwall', 'Cornwall'),
  ('Polperro', 'Cornwall', 'Cornwall'),
  ('Ponsanooth', 'Cornwall', 'Cornwall'),
  ('Porthleven', 'Cornwall', 'Cornwall'),
  ('Portreath', 'Cornwall', 'Cornwall'),
  ('Poundstock', 'Cornwall', 'Cornwall'),
  ('Probus', 'Cornwall', 'Cornwall'),
  ('Quethiock', 'Cornwall', 'Cornwall'),
  ('Redruth', 'Cornwall', 'Cornwall'),
  ('Roche', 'Cornwall', 'Cornwall'),
  ('Ruanlanihorne', 'Cornwall', 'Cornwall'),
  ('Saltash', 'Cornwall', 'Cornwall'),
  ('Sancreed', 'Cornwall', 'Cornwall'),
  ('Sennen', 'Cornwall', 'Cornwall'),
  ('Sheviock', 'Cornwall', 'Cornwall'),
  ('Sithney', 'Cornwall', 'Cornwall'),
  ('South Hill', 'Cornwall', 'Cornwall'),
  ('South Petherwin', 'Cornwall', 'Cornwall'),
  ('St Agnes', 'Cornwall', 'Cornwall'),
  ('St Allen', 'Cornwall', 'Cornwall'),
  ('St Anthony-in-Meneage', 'Cornwall', 'Cornwall'),
  ('St Austell', 'Cornwall', 'Cornwall'),
  ('St Austell Bay', 'Cornwall', 'Cornwall'),
  ('St Blaise', 'Cornwall', 'Cornwall'),
  ('St Breock', 'Cornwall', 'Cornwall'),
  ('St Breward', 'Cornwall', 'Cornwall'),
  ('St Buryan, Lamorna and Paul', 'Cornwall', 'Cornwall'),
  ('St Cleer', 'Cornwall', 'Cornwall'),
  ('St Clement', 'Cornwall', 'Cornwall'),
  ('St Clether', 'Cornwall', 'Cornwall'),
  ('St Columb Major', 'Cornwall', 'Cornwall'),
  ('St Day', 'Cornwall', 'Cornwall'),
  ('St Dennis', 'Cornwall', 'Cornwall'),
  ('St Dominick', 'Cornwall', 'Cornwall'),
  ('St Endellion', 'Cornwall', 'Cornwall'),
  ('St Enoder', 'Cornwall', 'Cornwall'),
  ('St Erme', 'Cornwall', 'Cornwall'),
  ('St Erth', 'Cornwall', 'Cornwall'),
  ('St Ervan', 'Cornwall', 'Cornwall'),
  ('St Eval', 'Cornwall', 'Cornwall'),
  ('St Ewe', 'Cornwall', 'Cornwall'),
  ('St Gennys', 'Cornwall', 'Cornwall'),
  ('St Germans', 'Cornwall', 'Cornwall'),
  ('St Goran', 'Cornwall', 'Cornwall'),
  ('St Hilary', 'Cornwall', 'Cornwall'),
  ('St Issey', 'Cornwall', 'Cornwall'),
  ('St Ive and Pensilva', 'Cornwall', 'Cornwall'),
  ('St Ives', 'Cornwall', 'Cornwall'),
  ('St John', 'Cornwall', 'Cornwall'),
  ('St Juliot', 'Cornwall', 'Cornwall'),
  ('St Just', 'Cornwall', 'Cornwall'),
  ('St Just in Roseland', 'Cornwall', 'Cornwall'),
  ('St Keverne', 'Cornwall', 'Cornwall'),
  ('St Kew', 'Cornwall', 'Cornwall'),
  ('St Keyne and Trewidland', 'Cornwall', 'Cornwall'),
  ('St Levan', 'Cornwall', 'Cornwall'),
  ('St Mabyn', 'Cornwall', 'Cornwall'),
  ('St Martin-by-Looe', 'Cornwall', 'Cornwall'),
  ('St Martin-in-Meneage', 'Cornwall', 'Cornwall'),
  ('St Martin''s', 'Cornwall', 'Cornwall'),
  ('St Mary''s', 'Cornwall', 'Cornwall'),
  ('St Mellion', 'Cornwall', 'Cornwall'),
  ('St Merryn', 'Cornwall', 'Cornwall'),
  ('St Mewan', 'Cornwall', 'Cornwall'),
  ('St Michael Caerhays', 'Cornwall', 'Cornwall'),
  ('St Michael Penkevil', 'Cornwall', 'Cornwall'),
  ('St Michael''s Mount', 'Cornwall', 'Cornwall'),
  ('St Minver Highlands', 'Cornwall', 'Cornwall'),
  ('St Minver Lowlands', 'Cornwall', 'Cornwall'),
  ('St Neot', 'Cornwall', 'Cornwall'),
  ('St Newlyn East', 'Cornwall', 'Cornwall'),
  ('St Pinnock', 'Cornwall', 'Cornwall'),
  ('St Sampson', 'Cornwall', 'Cornwall'),
  ('St Stephen-in-Brannel', 'Cornwall', 'Cornwall'),
  ('St Stephens by Launceston Rural', 'Cornwall', 'Cornwall'),
  ('St Teath', 'Cornwall', 'Cornwall'),
  ('St Thomas the Apostle Rural', 'Cornwall', 'Cornwall'),
  ('St Tudy', 'Cornwall', 'Cornwall'),
  ('St Veep', 'Cornwall', 'Cornwall'),
  ('St Wenn', 'Cornwall', 'Cornwall'),
  ('St Winnow', 'Cornwall', 'Cornwall'),
  ('Stithians', 'Cornwall', 'Cornwall'),
  ('Stokeclimsland', 'Cornwall', 'Cornwall'),
  ('Tintagel', 'Cornwall', 'Cornwall'),
  ('Torpoint', 'Cornwall', 'Cornwall'),
  ('Towednack', 'Cornwall', 'Cornwall'),
  ('Tregony with Cuby', 'Cornwall', 'Cornwall'),
  ('Tremaine', 'Cornwall', 'Cornwall'),
  ('Tresco', 'Cornwall', 'Cornwall'),
  ('Tresmeer', 'Cornwall', 'Cornwall'),
  ('Trevalga', 'Cornwall', 'Cornwall'),
  ('Treverbyn', 'Cornwall', 'Cornwall'),
  ('Trewen', 'Cornwall', 'Cornwall'),
  ('Truro', 'Cornwall', 'Cornwall'),
  ('Tywardreath and Par', 'Cornwall', 'Cornwall'),
  ('Veryan', 'Cornwall', 'Cornwall'),
  ('Wadebridge', 'Cornwall', 'Cornwall'),
  ('Warbstow', 'Cornwall', 'Cornwall'),
  ('Warleggan', 'Cornwall', 'Cornwall'),
  ('Week St Mary', 'Cornwall', 'Cornwall'),
  ('Wendron', 'Cornwall', 'Cornwall'),
  ('Werrington', 'Cornwall', 'Cornwall'),
  ('Whitstone', 'Cornwall', 'Cornwall'),
  ('Withiel', 'Cornwall', 'Cornwall'),
  ('Zennor', 'Cornwall', 'Cornwall')
on conflict (name, district) do nothing;
