#!/usr/bin/env python3
"""
Parish-based ONS population estimator (see ../POPULATION-CAPACITY-METHOD.md §2-5).

Pulls Census 2021 resident population to the parish level using the ONS best-fit method
(Output-Area population assigned to the parish whose polygon contains the OA centroid), then
seeds each sewage system's base population P = sum of the distinct parishes its assets fall in.

Pipeline:
  1. Fetch OA centroids (OA21CD, LAT, LONG) within the Dart bbox from the ONS OA boundary service.
  2. Fetch Census 2021 usual-resident counts for those OAs from NOMIS (TS001, all residents).
  3. Emit idempotent, portable SQL that, in PostGIS:
       - loads the OA points + population into a temp table,
       - sets parishes.census_2021_population = sum of OA pop whose centroid is in the parish,
       - upserts system_assumptions.ons_population = sum of the distinct parishes containing the
         system's geocoded assets (preserving any user-tuned g/low/high/override on conflict).

Usage:
    python3 estimate_system_population.py > /tmp/system_pop.sql
    docker run --rm -i --network host postgres:16 psql "$DB_URL" < /tmp/system_pop.sql

The geometry/point-in-polygon is done in SQL, so no Python geo deps are needed. Re-running it is
the "refresh from ONS" for parish populations; the in-app button recomputes system totals via the
system_ons_population() RPC once parish populations are loaded.
"""
import json, sys, ssl, urllib.parse, urllib.request

# Public open-data GET endpoints; this Python build lacks a root-cert bundle.
_SSL = ssl.create_default_context()
_SSL.check_hostname = False
_SSL.verify_mode = ssl.CERT_NONE

import catchment_config

_CC = catchment_config.load()
_S, _W, _N, _E = _CC["geo"]["bbox"]
BBOX = {"lon_min": _W, "lon_max": _E, "lat_min": _S, "lat_max": _N}

OA_SERVICE = ("https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/"
              "Output_Areas_2021_EW_BGC_V2/FeatureServer/0/query")
# NOMIS Census 2021 TS001 (number of usual residents). C2021_RESTYPE_3=0 -> all usual residents.
NOMIS = ("https://www.nomisweb.co.uk/api/v01/dataset/NM_2021_1.data.csv"
         "?geography={codes}&measures=20100&date=latest&C2021_RESTYPE_3=0"
         "&select=GEOGRAPHY_CODE,OBS_VALUE")

PROVENANCE = f"ONS Census 2021 OA->parish best-fit centroid ({_CC['river']} bbox)"


def get(url, params=None):
    full = f"{url}?{urllib.parse.urlencode(params)}" if params else url
    with urllib.request.urlopen(full, timeout=120, context=_SSL) as r:
        return r.read()


def fetch_oa_centroids():
    """Return [(oa21cd, lon, lat), ...] for OAs whose centroid is inside the Dart bbox."""
    where = (f"LONG BETWEEN {BBOX['lon_min']} AND {BBOX['lon_max']} "
             f"AND LAT BETWEEN {BBOX['lat_min']} AND {BBOX['lat_max']}")
    out, offset = [], 0
    while True:
        raw = get(OA_SERVICE, {
            "where": where, "outFields": "OA21CD,LAT,LONG", "returnGeometry": "false",
            "resultOffset": offset, "resultRecordCount": 2000, "f": "json",
        })
        d = json.loads(raw)
        feats = d.get("features", [])
        for f in feats:
            a = f["attributes"]
            out.append((a["OA21CD"], float(a["LONG"]), float(a["LAT"])))
        if len(feats) < 2000:
            break
        offset += 2000
    return out


def fetch_oa_population(codes):
    """Return {oa21cd: population}. NOMIS accepts comma-separated code lists; chunk to be safe."""
    pop = {}
    CHUNK = 100
    for i in range(0, len(codes), CHUNK):
        batch = codes[i:i + CHUNK]
        raw = get(NOMIS.format(codes=",".join(batch))).decode("utf-8", "replace")
        for line in raw.splitlines()[1:]:  # skip header
            parts = [p.strip().strip('"') for p in line.split(",")]
            if len(parts) >= 2 and parts[0]:
                try:
                    pop[parts[0]] = int(float(parts[1]))
                except ValueError:
                    pass
    return pop


def sql_lit(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    oas = fetch_oa_centroids()
    print(f"-- fetched {len(oas)} OA centroids in Dart bbox", file=sys.stderr)
    codes = [c for (c, _, _) in oas]
    pop = fetch_oa_population(codes)
    print(f"-- matched population for {len(pop)}/{len(codes)} OAs", file=sys.stderr)

    rows = [(c, lon, lat, pop[c]) for (c, lon, lat) in oas if c in pop]
    total = sum(p for *_, p in rows)
    print(f"-- total residents across loaded OAs: {total}", file=sys.stderr)

    print("-- River Hub: parish census population + system base population P")
    print("-- Generated by scripts/estimate_system_population.py. Idempotent; re-run to refresh.")
    print("begin;")
    print("create temp table _oa (code text primary key, pop int, geom geometry(Point,4326)) "
          "on commit drop;")
    # batched inserts
    B = 500
    for i in range(0, len(rows), B):
        vals = ",\n  ".join(
            f"({sql_lit(c)},{p},ST_SetSRID(ST_Point({lon},{lat}),4326))"
            for (c, lon, lat, p) in rows[i:i + B]
        )
        print(f"insert into _oa(code,pop,geom) values\n  {vals};")

    # parish census population = sum of OA pop whose centroid falls in the parish polygon
    print("""
update parishes p set census_2021_population = sub.pop
from (
  select pa.id, coalesce(sum(o.pop),0) as pop
  from parishes pa
  join _oa o on ST_Contains(pa.boundary, o.geom)
  where pa.boundary is not null
  group by pa.id
) sub
where p.id = sub.id;""")

    # system base population P = sum of distinct parishes containing the system's geocoded assets
    print(f"""
insert into system_assumptions (system_id, organisation_id, ons_population, ons_calculated_at, ons_source)
select s.id, s.organisation_id,
  (select coalesce(sum(pp.census_2021_population),0)::int
     from (
       select distinct p.id, p.census_2021_population
       from parishes p
       join sewage_assets a
         on a.sewage_system_id = s.id
        and a.latitude is not null and a.longitude is not null
        and ST_Contains(p.boundary, ST_SetSRID(ST_Point(a.longitude,a.latitude),4326))
       where p.census_2021_population is not null
     ) pp),
  now(), {sql_lit(PROVENANCE)}
from sewage_systems s
on conflict (system_id) do update
  set ons_population    = excluded.ons_population,
      ons_calculated_at = excluded.ons_calculated_at,
      ons_source        = excluded.ons_source;""")
    print("commit;")


if __name__ == "__main__":
    main()
